export const GET_RESR_SUCCESS = 'GET_RESR_SUCCESS'
export const GET_RESR_FAILED = 'GET_RESR_FAILED'
export const LOADING = 'LOADING'
export const GET_RESR_DATA_SUCCESS = 'GET_RESR_DATA_SUCCESS'
export const GET_RESR_DATA_FAILED = 'GET_RESR_DATA_FAILED'
export const GET_RESR_DATA_LOADING = 'GET_RESR_DATA_LOADING'
export const GET_RESRBYID_FAILED = 'GET_RESRBYID_FAILED'
export const GET_RESRBYID_SUCCESS = 'GET_RESRBYID_SUCCESS'
export const LOADING_BYID = 'LOADING_BYID'
export const LOADING_BYID_POST = 'LOADING_BYID_POST'
export const POST_RESRBYID_SUCCESS = 'POST_RESRBYID_SUCCESS'
export const POST_RESRBYID_FAILED = 'POST_RESRBYID_FAILED'


export const GET_RESR_BYDATE_SUCCESS = 'GET_RESR_BYDATE_SUCCESS'
export const GET_RESR_BYDATE_FAILED = 'GET_RESR_BYDATE_FAILED'
export const SELECTED_DATE = 'SELECTED_DATE'
export const IS_DATE_PIKER_OPEND = 'IS_DATE_PIKER_OPEND'

