export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOADING = 'LOADING'
export const DELETE_MESSAGES = "DELETE_MESSAGES"
export const USER_INFORMATIONS_FAILED = "USER_INFORMATIONS_FAILED"
export const USER_INFORMATIONS = "USER_INFORMATIONS"


